namespace: default
component: admin
part-of: mosip
activeProfileEnv: mz 
springConfigLabel: master
configServerUrl: http://config-server/config
sandboxDomainName: test-sandbox.southindia.cloudapp.azure.com
ingress:
   namespace: default
artifactoryUrl: http://13.71.87.138:8040
probe:
  initialDelay: 30  # Seconds
  period: 30 # Seconds
services:
  admin: 
    serviceName: admin-service
    dockerImage: mosipdev/admin-service
    dockerTag: 1.0.6
    containerPort: 8098
    servicePort: 80
    ingressPath: /v1/admin
    healthUrl: /v1/admin/actuator/health
  ui:
    serviceName: admin-ui
    dockerImage: mosipdev/admin-ui
    dockerTag: 1.0.10
    containerPort: 80
    servicePort: 80
    configName: amdin-ui-config # ConfigMap name
    apiHost: https://{{ .Values.sandboxDomainName }}/
    ingressPath: /admin-ui
