---
# This script runs all the init SQL queries and populates all tables with
# test data 
# IMPORTANT: Init only run once.  To run again, delete the init.lock file in 
# postgres folder

# Copy dml files - typically needed to replace default master data with 
# country's data
- name: Check if init lock file exists (ie. init has already been done once)
  stat:
    path: '{{postgres_init_lock_file}}'
  become: yes
  register: out

- debug:
    msg: Init has already been done once. Skipping init.
  when: out.stat.exists
  
- meta: end_play  # Exit
  when: out.stat.exists

- name: Copy any custom dml files
  copy:
    src: '{{item.value.dml}}/' 
    dest: '{{item.value.sql_path}}/{{item.key}}/dml/' 
  when: item.value.dml is defined
  loop: '{{databases | dict2items}}'

- include: init_db.yml
  vars:
    pg_db_name: '{{item.key}}'
    pg_sql_path: '{{item.value.sql_path}}'
  with_items: '{{databases | dict2items}}'
        
# After successful init, create a lockfile to not init again 
- name: Create init lock file to not re-init again
  file:
    path: '{{postgres_init_lock_file}}'
    state: touch
  become: yes
