---
# This script runs all the init SQL queries and populates all tables with
# test data 
# TODO: Init should not happend if Postgres has valuable data
- name: Create logs directory
  file:
    path: "{{logs_dir}}"
    state: directory
    mode: '0755'

# Get db_ip. Since Postgres is published as a node port we get the IP of any
# work node.
- name: Get db_ip
  command: "kubectl get node --selector='!node-role.kubernetes.io/master' -o json"
  register: out

- name: Get DB port IP
  command: 'kubectl get service -o json postgres'
  register: out

- set_fact:
    db_port: '{{(out.stdout | from_json).spec.ports[0].nodePort}}'
 
- include: init_db.yml
  with_items:
    - mosip_kernel
    - mosip_master
    - mosip_iam
    - mosip_audit
    - mosip_idrepo
    - mosip_idmap        
        
