apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.generators.encryptsalt.name }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.generators.encryptsalt.name }}
    component: {{ .Values.component }} 
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
    
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.generators.encryptsalt.name }} 
        component: {{ .Values.component }} 
    spec:
      restartPolicy: Never  # This is one time job
      containers:
      - name: {{ .Values.generators.encryptsalt.name }} 
        image: {{ .Values.generators.encryptsalt.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: spring_config_name_env
          value: id-authentication
        - name: is_glowroot_env
          value: absent
        - name: table_name
          value: javax.persistence.jdbc.uinEncryptTable 
