apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.internal.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.internal.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  {{ $podconfig := .Values.services.internal.podconfig }}
  replicas: {{ $podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.internal.serviceName }}
  minReadySeconds: {{ $podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ $podconfig.maxUnavailable }}
      maxSurge: {{ $podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.internal.serviceName }} 
        component: {{ .Values.component }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.internal.serviceName }} 
        image: {{ .Values.services.internal.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- include "resourcesDefinition" (dict "res" $podconfig.resources) | indent 8 }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }} 
        - name: PKCS11_PROXY_SOCKET
          value: {{ .Values.services.internal.hsmUrl }} 
        - name: iam_adapter_url_env
          value: {{ .Values.iamAdapterUrl }}
        - name: zip_file_path
          value: {{ .Values.services.internal.hsmClientZipPath }}
        - name: mosip_biosdk_service
          value: {{ .Values.biosdkServiceUrl }}
        - name: JDK_JAVA_OPTIONS
          value: {{ $podconfig.java_opts }}
        ports:
        - containerPort: {{ .Values.services.internal.containerPort }}
        volumeMounts:

        readinessProbe:
          httpGet:
            path: {{ .Values.services.internal.healthUrl }} 
            port: {{ .Values.services.internal.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
#        livenessProbe:
#          httpGet:
#            path: {{ .Values.services.internal.healthUrl }} 
#            port: {{ .Values.services.internal.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }}
#
