apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.otp.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.otp.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.otp.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.otp.serviceName }} 
        component: {{ .Values.component }} 
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      initContainers:  # TODO: Temporarily added as a workaround. Duplicate key issue. 
      - name: wait-for-auth
        image: ellerbrock/alpine-bash-curl-ssl
        command: ['sh', '-c', "while !(curl --connect-timeout 3 -X GET  http://ida-auth-service/idauthentication/v1/auth/actuator/health | grep status);do sleep 3;done"]
      containers:
      - name: {{ .Values.services.otp.serviceName }} 
        image: {{ .Values.services.otp.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }} 
        - name: PKCS11_PROXY_SOCKET
          value: {{ .Values.services.otp.hsmUrl }} 
        ports:
        - containerPort: {{ .Values.services.otp.containerPort }}

        {{- include "logger.mount" .  | indent 8}}

        readinessProbe:
          httpGet:
            path: {{ .Values.services.otp.healthUrl }} 
            port: {{ .Values.services.otp.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
  #      livenessProbe:
  #        httpGet:
  #          path: {{ .Values.services.otp.healthUrl }} 
  #          port: {{ .Values.services.otp.containerPort }} 
  #        initialDelaySeconds: {{ .Values.probe.initialDelay }} 
  #        periodSeconds: {{ .Values.probe.period }}
  #
      {{- include "logger.sidecar" .  | indent 6}}

      {{- include "logger.volume" .  | indent 6}}
