apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.admin.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.admin.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.admin.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.admin.serviceName }} 
        component: {{ .Values.component }} 
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.admin.serviceName }} 
        image: {{ .Values.services.admin.dockerImage }} 
        imagePullPolicy: {{ .Values.imagePullPolicy }} 
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }}
        - name: mosipbox_public_url
          value: {{ .Values.sitePublicUrl }}
        ports:
        - containerPort: {{ .Values.services.admin.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.admin.healthUrl }} 
            port: {{ .Values.services.admin.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
#        livenessProbe:
#          httpGet:
#            path: {{ .Values.services.admin.healthUrl }} 
#            port: {{ .Values.services.admin.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }}
