apiVersion: v1
data:
  config.json: '{"baseUrl":"{{ tpl .Values.services.ui.apiHost . }}",  "adminUrl" : "/admin-ui/", "primaryLangCode": "eng", "secondaryLangCode": "ara"}'
kind: ConfigMap
metadata:
  name: {{ .Values.services.ui.configName }}
  namespace: {{ .Release.Namespace }} 

