namespace: default
component: pms
part-of: mosip
activeProfileEnv: mz 
springConfigLabel: master
configServerUrl: http://config-server/config
ingress:
   namespace: default
artifactoryUrl: http://13.71.87.138:8040
probe:
  initialDelay: 30  # Seconds
  period: 30 # Seconds
services:
  misp: 
    serviceName: pms-misp-service
    dockerImage: mosipdev/pmp-misp-service
    dockerTag: 1.0.0
    containerPort: 9100
    servicePort: 80
    ingressPath: /partnermanagement/v1/misps
    healthUrl: /partnermanagement/v1/misps/actuator/health
  pm:
    serviceName: pms-partner-management-service
    dockerImage: mosipdev/pmp-partner-management-service
    dockerTag: 1.0.0
    containerPort: 9102
    servicePort: 80
    ingressPath: /partnermanagement/v1/pmpartners
    healthUrl: /partnermanagement/v1/pmpartners/actuator/health
  partner:
    serviceName: pms-partner-service
    dockerImage: mosipdev/pmp-partner-service
    dockerTag: 1.0.0
    containerPort: 9103
    servicePort: 80
    ingressPath: /partnermanagement/v1/partners
    healthUrl: /partnermanagement/v1/partners/actuator/health
  policy:
    serviceName: pms-policy-management-service
    dockerImage: mosipdev/pmp-policy-management-service
    dockerTag: 1.0.0
    containerPort: 9101
    servicePort: 80
    ingressPath: /partnermanagement/v1/policies
    healthUrl: /partnermanagement/v1/policies/actuator/health
