apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.component }}
  namespace: {{ .Release.Namespace}} 
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.com/health-checks: "true"
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.services.ingress }}
        backend:
          serviceName: {{ .Values.services.serviceName }}
          servicePort: {{ .Values.services.servicePort }}

