# This script downloads kernel config jar, builds docker and deploys it
# The docker is pushed to a local registry with SSL as Kubernetes 
# deployment needs such a registry.
---
- name: Create a tmp directory
  file:
    path: '{{tmp_dir}}'
    state: directory
    mode: '0755'

- name: Download kernel-server-config tar
  get_url:
    url: "{{artifactory_uri}}/artifactory/libs-release-local/io/mosip/kernel/kernel-config-server/{{modules['kernel-config-server']['version']}}/kernel-config-server-{{modules['kernel-config-server']['version']}}.jar"
    dest: "{{role_path}}/files/kernel-config-server-{{modules['kernel-config-server']['version']}}.jar"

- name: Build docker and push it local registry  
  docker_image:
    name: '{{local_registry}}/kernel-config-server'
    tag: "{{modules['kernel-config-server']['version']}}"
    push: yes
    source: build
    build:
      path: '{{role_path}}/files' 
      pull: yes
      args:
        version: "{{modules['kernel-config-server']['version']}}"
        git_uri: 'http://gitrepo/{{config_gitrepo_name}}'
      #TODO: pickup gitrepo from service name

- name: Kubernetes yml file from template 
  template:
     src: k8s_deploy.xml.j2
     dest: '{{tmp_dir}}/k8s_deploy.yml'

- name: Deploy on Kubernetes
  k8s:
    src: '{{tmp_dir}}/k8s_deploy.yml'  
    state: present
    wait: yes
    wait_timeout: 120 

