onboarding:
  modules:
    - name: ida
      enabled: true
    - name: print
      enabled: false
    - name: abis
      enabled: false
    - name: resident
      enabled: false
    - name: mobileid
      enabled: false
    - name: digitalcard
      enabled: false
    - name: esignet
      enabled: false
    - name: demo-oidc
      enabled: false
    - name: resident-oidc
      enabled: false
    - name: mimoto-keybinding
      enabled: true
