---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: {{ .Values.services.config_server.podconfig.replicas }} 
  selector:
    matchLabels:
      app: {{ .Values.name }}
  minReadySeconds: {{ .Values.services.config_server.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.config_server.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.config_server.podconfig.maxSurge }} 
  template:
    metadata:
      labels:
        app: {{ .Values.name }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.docker.image }}
        imagePullPolicy: Always
        {{ $resources := .Values.services.config_server.podconfig.resources }}
        {{- include "resourcesDefinition" (dict "res" $resources) | indent 8 }}
        env:
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS 
          value: {{ .Values.gitRepo.searchFolders }}
        - name: ENCRYPT_KEY
          value: {{ .Values.encryptKey }}
        - name: SPRING_CLOUD_CONFIG_SERVER_OVERRIDES_MOSIPBOX_PUBLIC_URL  # Sets mosip.public.url
          value: {{  .Values.sandboxPublicUrl }}
        {{ if eq .Values.localRepo.enabled true }}
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: {{ .Values.localRepo.mountPath }}
        {{ else }}
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: {{ .Values.gitRepo.uri }}
        {{ if eq .Values.gitRepo.private true }}
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
          value: {{ .Values.gitRepo.username }} 
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
          value: {{ .Values.gitRepo.password }} 
        {{ end }} 
        {{ end }}
        ports:
        - containerPort: {{ .Values.docker.containerPort }} 
        readinessProbe:
          tcpSocket:
            port: {{ .Values.docker.containerPort }}  # All defaults used
{{ if eq .Values.localRepo.enabled true }}
        volumeMounts:
        - name: repo
          mountPath: {{ .Values.localRepo.mountPath }} 
      volumes:
      - name: repo 
        persistentVolumeClaim:
          claimName: {{ .Values.localRepo.pvc.name }}
{{ end }}

