apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.generators.cred.name }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.generators.cred.name }}
    component: {{ .Values.component }} 
  annotations:
#    "helm.sh/hook": pre-install
#    "helm.sh/hook-delete-policy": hook-succeeded
    
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.generators.cred.name }} 
        component: {{ .Values.component }} 
    spec:
      restartPolicy: Never  # This is one time job
      containers:
      - name: {{ .Values.generators.cred.name }} 
        image: {{ .Values.generators.cred.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: absent
        - name: olv_partner_ids_env
          value: "mpartner-default-auth"
        - name: skip_existing_cred_requests_for_partner_env
          value: "true"

