apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.biosvc.serviceName }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.services.biosvc.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.biosvc.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.biosvc.serviceName }} 
    spec:
      containers:
      - name: {{ .Values.services.biosvc.serviceName }} 
        image: {{ .Values.services.biosvc.dockerImage }}:{{ .Values.services.biosvc.dockerTag }} 
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: absent
        ports:
        - name: verticle-port
          containerPort: {{ .Values.services.biosvc.ports.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.biosvc.healthUrl }} 
            port: {{ .Values.services.biosvc.ports.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
 #       livenessProbe:
 #         httpGet:
 #           path: {{ .Values.services.biosvc.healthUrl }} 
 #           port: {{ .Values.services.biosvc.ports.containerPort }} 
 #         initialDelaySeconds: {{ .Values.probe.initialDelay }} 
 #         periodSeconds: {{ .Values.probe.period }} 
