apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.external.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.external.serviceName }}
    
spec:
  replicas: {{ .Values.services.external.podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.external.serviceName }} 
  minReadySeconds: {{ .Values.services.external.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.external.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.external.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.external.serviceName }} 
        component: service-hazelcast-server
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.external.serviceName }} 
        image: {{ .Values.services.external.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }}
        - name: mosipbox_public_url
          value: {{ .Values.sitePublicUrl }}
        ports:
        - name: eventbus-port
          containerPort: {{ .Values.services.external.ports.eventbusPort }}
        - name: hazelcast-port
          containerPort: {{ .Values.services.external.ports.hazelcastPort }}
        - name: verticle-port
          containerPort: {{ .Values.services.external.ports.containerPort }}

        {{- include "logger.mount" .  | indent 8}}

      {{- include "logger.sidecar" .  | indent 6}}

      {{- include "logger.volume" .  | indent 6}}
#        readinessProbe:
#          httpGet:
#            path: {{ .Values.services.bio.healthUrl }} 
#            port: {{ .Values.services.bio.ports.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }} 
#        livenessProbe: 
#          httpGet:
#            path: {{ .Values.services.external.healthUrl }} 
#            port: {{ .Values.services.external.ports.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }} 
