apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.group3.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.group3.serviceName }}
    
spec:
  {{ $podconfig := .Values.services.group3.podconfig }} 
  replicas: {{ $podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.group3.serviceName }}
  minReadySeconds: {{ $podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ $podconfig.maxUnavailable }}
      maxSurge: {{ $podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.group3.serviceName }} 
        component: service-hazelcast-server
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.group3.serviceName }} 
        image: {{ .Values.services.group3.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- include "resourcesDefinition" (dict "res" $podconfig.resources) | indent 8 }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }}
        - name: JDK_JAVA_OPTIONS
          value: {{ $podconfig.java_opts }}
        ports:
        - name: hazelcast
          containerPort: {{ .Values.services.group3.ports.hazelcastPort }}
        - name: abishandler-eb
          containerPort: {{ .Values.services.abishandler.ports.eventbusPort }}
        - name: abishandler-vt
          containerPort: {{ .Values.services.abishandler.ports.containerPort }}
        - name: abismid-eb
          containerPort: {{ .Values.services.abismid.ports.eventbusPort }}
        - name: abismid-vt
          containerPort: {{ .Values.services.abismid.ports.containerPort }}
        - name: bio-eb
          containerPort: {{ .Values.services.bio.ports.eventbusPort }}
        - name: bio-vt
          containerPort: {{ .Values.services.bio.ports.containerPort }}
        - name: manual-eb
          containerPort: {{ .Values.services.manual.ports.eventbusPort }}
        - name: manual-vt
          containerPort: {{ .Values.services.manual.ports.containerPort }}

        readinessProbe:
          httpGet:
            path: {{ .Values.services.group3.healthUrl }}
            port: {{ .Values.services.group3.ports.containerPort }}
          periodSeconds: {{ .Values.probe.period }}
          timeoutSeconds: {{ .Values.probe.timeout }}
          failureThreshold: {{ .Values.probe.failureThreshold }}
        livenessProbe:
          httpGet:
            path: {{ .Values.services.group3.healthUrl }}
            port: {{ .Values.services.group3.ports.containerPort }}
          periodSeconds: {{ .Values.probe.livenessPeriod }}
          timeoutSeconds: {{ .Values.probe.timeout }}
          failureThreshold: {{ .Values.probe.failureThreshold }}
        startupProbe:
          httpGet:
            path: {{ .Values.services.group3.healthUrl }}
            port: {{ .Values.services.group3.ports.containerPort }}
          failureThreshold: {{ .Values.probe.failureThreshold }}
          periodSeconds: {{ .Values.probe.startupPeriod }}
          timeoutSeconds: {{ .Values.probe.timeout }}
          initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
