apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.group2.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.group2.serviceName }}
    
spec:
  {{ $podconfig := .Values.services.group2.podconfig }} 
  replicas: {{ $podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.group2.serviceName }}
  minReadySeconds: {{ $podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ $podconfig.maxUnavailable }}
      maxSurge: {{ $podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.group2.serviceName }} 
        component: service-hazelcast-server
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.group2.serviceName }} 
        image: {{ .Values.services.group2.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- include "resourcesDefinition" (dict "res" $podconfig.resources) | indent 8 }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }}
        - name: JDK_JAVA_OPTIONS
          value: {{ $podconfig.java_opts }}
        ports:
        - name: hazelcast
          containerPort: {{ .Values.services.group2.ports.hazelcastPort }}
        - name: qt-eventbus
          containerPort: {{ .Values.services.quality.ports.eventbusPort }}
        - name: qt-verticle
          containerPort: {{ .Values.services.quality.ports.containerPort }}
        - name: not-eventbus
          containerPort: {{ .Values.services.notification.ports.eventbusPort }}
        - name: not-verticle
          containerPort: {{ .Values.services.notification.ports.containerPort }}
        - name: msgeventbus
          containerPort: {{ .Values.services.msg.ports.eventbusPort }}
        - name: msgverticle
          containerPort: {{ .Values.services.msg.ports.containerPort }}

#        readinessProbe:  # TODO: Uncomment this or put a actuator health url
#          httpGet:
#            path: {{ .Values.services.abishandler.healthUrl }} 
#            port: {{ .Values.services.abishandler.ports.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }} 
#        livenessProbe:
#          httpGet:
#            path: {{ .Values.services.abishandler.healthUrl }} 
#            port: {{ .Values.services.abishandler.ports.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }} 
