apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.manual.serviceName }} 
  namespace: {{ .Release.Namespace }} 
spec:
  ports:
  - port: {{ .Values.services.manual.ports.servicePort }}
    targetPort: {{ .Values.services.manual.ports.containerPort }}
  selector:
    app: {{ .Values.services.manual.serviceName }} 
