apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.osi.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.osi.serviceName }}
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.osi.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.osi.serviceName }} 
        component: service-hazelcast-server
    spec:
      serviceAccountName: {{ .Values.service_account }}
      securityContext:
        runAsUser: {{ .Values.podUserId }}
        runAsGroup: {{ .Values.podUserGid }}
      {{- include "logger.volume" .  | indent 6}}
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.osi.serviceName }} 
        image: {{ .Values.services.osi.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          runAsUser: {{ .Values.containerUserId }}
          runAsGroup: {{ .Values.containerUserGid }}
          allowPrivilegeEscalation: false
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }}
        ports:
        - name: eventbus-port
          containerPort: {{ .Values.services.osi.ports.eventbusPort }}
        - name: hazelcast-port
          containerPort: {{ .Values.services.osi.ports.hazelcastPort }}
        - name: verticle-port
          containerPort: {{ .Values.services.osi.ports.containerPort }}

        {{- include "logger.mount" .  | indent 8}}

      {{- include "logger.sidecar" .  | indent 6}}

#      {{- include "logger.volume" .  | indent 6}}
#        readinessProbe:
#          httpGet:
#            path: {{ .Values.services.osi.healthUrl }} 
#            port: {{ .Values.services.osi.ports.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }} 
#        livenessProbe:
#          httpGet:
#            path: {{ .Values.services.osi.healthUrl }} 
#            port: {{ .Values.services.osi.ports.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }} 
