apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.validator.serviceName }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.services.validator.serviceName }}
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.validator.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.validator.serviceName }} 
        component: service-hazelcast-server
    spec:
      containers:
      - name: {{ .Values.services.validator.serviceName }} 
        image: {{ .Values.services.validator.dockerImage }}:{{ .Values.services.validator.dockerTag }} 
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: absent
        ports:
        - name: eventbus-port
          containerPort: {{ .Values.services.validator.ports.eventbusPort }}
        - name: hazelcast-port
          containerPort: {{ .Values.services.validator.ports.hazelcastPort }}
        - name: verticle-port
          containerPort: {{ .Values.services.validator.ports.containerPort }}
#        readinessProbe:
#          httpGet:
#            path: {{ .Values.services.validator.healthUrl }} 
#            port: {{ .Values.services.validator.ports.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }} 
        livenessProbe:
          httpGet:
            path: {{ .Values.services.validator.healthUrl }} 
            port: {{ .Values.services.validator.ports.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
