# Tasks here create a self signed certificate for Nginx
  - name: Create various dirs
    file:
      path: '{{ssl.ca.selfsigned.certificate | dirname}}'
      state: directory 
    become: yes

  - name: Create various dirs
    file:
      path: '{{ssl.ca.selfsigned.certificate_key| dirname}}'
      mode: '700'
      state: directory 
    become: yes

  - name: Create various dirs
    file:
      path: '{{ssl.ca.selfsigned.csr | dirname}}'
      mode: '700'
      state: directory 
    become: yes

  - name: Generate private key
    openssl_privatekey:
      path: '{{ssl.ca.selfsigned.certificate_key}}' 
    become: yes
     
  - set_fact:
      selfsigned_ip: ''

  - name: Check if host name is ip address
    set_fact:
      selfsigned_ip: 'IP:{{ssl.ca.selfsigned.common_name}}'
    when: (ssl.ca.selfsigned.common_name | ipaddr) != false

  - debug:
       msg: 'Adding alt name: "{{selfsigned_ip}}" to self signed certificate'

  - name: Generate an OpenSSL Certificate Signing Request
    openssl_csr:
      path: '{{ssl.ca.selfsigned.csr}}' 
      privatekey_path: '{{ssl.ca.selfsigned.certificate_key}}' 
      common_name: '{{ssl.ca.selfsigned.common_name}}'
      subject_alt_name: '{{selfsigned_ip}}'
    become: yes

  - name: Generate a Self Signed OpenSSL certificate
    openssl_certificate:
      path: '{{ssl.ca.selfsigned.certificate}}'  
      privatekey_path: '{{ssl.ca.selfsigned.certificate_key}}' 
      csr_path: '{{ssl.ca.selfsigned.csr}}' 
      provider: selfsigned
      force: true
    become: yes

