---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.services.serviceName }}
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ .Values.services.serviceName }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.serviceName }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      containers:
      - name: {{ .Values.services.serviceName }}
        image: {{ .Values.services.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: biosdk_zip_file_path
          value: {{ .Values.biosdklibzip }}
        - name: biosdk_bioapi_impl
          value: {{ .Values.biosdklib }}
        ports:
        - containerPort: {{ .Values.services.containerPort }} 
