---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.services.activemq.podconfig.replicas }} 
  selector:
    matchLabels:
      app: {{ .Values.name }}
  minReadySeconds: {{ .Values.services.activemq.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.activemq.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.activemq.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.docker.image }}
        env:
        - name: ACTIVEMQ_CONFIG_MINMEMORY
          value: {{ .Values.docker.minmemory }}
        - name: ACTIVEMQ_CONFIG_MAXMEMORY
          value: {{ .Values.docker.maxmemory }}
        - name: ACTIVEMQ_CONFIG_STOREUSAGE
          value: {{ .Values.docker.storeusage }}
        - name: ACTIVEMQ_CONFIG_TEMPUSAGE
          value: {{ .Values.docker.tempusage }}
        - name: ACTIVEMQ_ADMIN_LOGIN
          value: admin
        - name: ACTIVEMQ_ADMIN_PASSWORD
          value: {{ .Values.adminPassword }} 
        ports:
        - containerPort: {{ .Values.docker.containerPort }} 
        readinessProbe:
          tcpSocket:
            port: {{ .Values.docker.containerPort }}  # All defaults used
        volumeMounts:
        - name: q-data
          mountPath: {{ .Values.mountPath }} 
      volumes:
      - name: q-data
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }} 
