- name: Local docker registry
  docker_container:
    name: '{{docker.local_registry.name}}'
    image: '{{docker.local_registry.image}}'
    state: '{{docker.local_registry_state}}'
    ports:
      - "{{docker.local_registry.port}}:{{docker.local_registry.port}}"
  become: yes 
