{{- $root := . -}}
{{- range $deploymentName, $val := $root.Values.deploymentsOnly }} 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ $deploymentName }}
    spec:
      initContainers:
      - name: config-server-availability-check
        image: centos:centos7
        command: [ "sh", "-c"]
        args:
        - while [ $(curl -sw '%{http_code}' $spring_config_url_env/actuator/health -o /dev/null) -ne 200 ]; do
            echo "config server not up at address $spring_config_url_env sleeping for 15 secs" ;
            sleep 15;
          done;
        env:
         - name: spring_config_url_env
           value: {{ $root.Values.commons.configServer.url }}
      containers:
      - name: {{ $deploymentName }}
        image: {{ $root.Values.commons.dockerRegistry.url }}/{{ .dockerImageName }}:{{ $root.Values.commons.dockerRegistry.dockerImageTag }}
        env:
        - name: active_profile_env
          value: {{ $root.Values.commons.configServer.activeProfile }}
        - name: spring_config_label_env
          value: {{ $root.Values.commons.configServer.configLabel }}
        - name: spring_config_url_env
          value: {{ $root.Values.commons.configServer.url }}
        ports:
        {{- range $portName, $portValue := $val.ports }} 
          - name: {{$portName}}
            containerPort: {{$portValue}}
        {{- end }}
        imagePullPolicy: Always
      imagePullSecrets:
      - name: {{ $root.Values.commons.dockerRegistry.pullSecret }}
{{- end }}