
name: postgres
password: postgres
defaultDb: keycloak # Default DB on Postgres
user: postgres
containerPort: 5432
localStorageName: postgres-local-storage
localStoragePath: /mnt/mosip_data/postgres  # Assumed that an empty directory is created beforehand
localStorageHostname: mzworker0  # Must match in plabooks.
pvcName: postgres-pvc
pvName: postgres-pv
pvSize: 1Gi
dockerImage: postgres
dockerTag: 12.2
nodePort: 30090
maxConnections: 1000 
