- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: 'admin'
    helm_chart: '{{charts_root}}/admin'
    is_template: true  
    helm_namespace: 'default'
    helm_values: '{{charts_root}}/admin/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}
