# This play install all the tools needed on the console for 
# further execution of automation. Here we have split tasks and roles into seperate
# play as tasks only run after roles if they are in the same play (for some reason)
# and for us sequencing is important.

- hosts: console
  gather_facts: true 
  tasks:
    - {name: 'Create tmp folder {{tmp_dir}}', file: {name: '{{tmp_dir}}', state: directory}}
    - {name: 'Create logs folder {{logs_dir}}', file: {name: '{{logs_dir}}', state: directory}}
    - {name: 'Create tmp yaml folder {{tmp_yamls}}', file: {name: '{{tmp_yamls}}', state: directory}}

- hosts: console
  gather_facts: true 
  roles:
     - {role: packages/vim, tags: [vim]}
     - {role: packages/pip, tags: [pip]}
     - {role: packages/python3, tags: [python3]} # Needed for letsencrypt and test scripts
     - {role: packages/jinja2, tags: [jinja2]}
     - {role: packages/pyyaml, tags: [pyyaml]}
     - {role: packages/docker, tags: [docker]}
     - {role: packages/kubectl, tags: [kubectl]}
     - {role: packages/psql, tags: [psql]}
     - {role: packages/openshift, tags: [openshift]}
     - {role: packages/helm-cli, tags: [helm-cli]}
     - {role: packages/policycoreutils-python, tags: [policy]}
     - {role: packages/requests3}
     - {role: packages/psycopg2}
     - {role: packages/crypto, tags: [crypto]}
     - {role: packages/tmux, tags: [tmux]}
     - {role: packages/bind-utils, tags: [bind-utils]}
     - {role: packages/pexpect, tags: [pexpect]}
     - {role: packages/jq, tags: [jq]}

  tasks: 
    - name: Set read permission to home directory needed for nginx 
      file:
        path: '{{lookup("env", "HOME")}}'
        mode: '755'
      become: yes
  
    - name: Change selinux to permissive mode.
      selinux:
        policy: targeted
        state: permissive
      become: yes

# Install some useful utils on all machines
- hosts: all
  gather_facts: true
  roles:
     - {role: packages/vim, tags: [vim]}
     - {role: packages/telnet, tags: [telnet]}
     - {role: packages/bind-utils, tags: [bind-utils]}  
     - {role: packages/net-tools, tags: [net-tools]}

# Change datetime of all machines to UTC
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - command: "date '+%Y-%m-%d %H:%M:%S'"
      register: date_utc
      environment:
        TZ: UTC
  
    - name: Change selinux to permissive mode.  
      selinux:
        policy: targeted
        state: permissive
      become: yes
