# Installs docker hub credentials. 
# Inputs expected while calling this playbook:
#   kube_config.
#
- hosts: console
  vars:
    mysecret: '{{secrets.docker.username}}:{{secrets.docker.password}}'
    dockerJson: '{ "auths": { "https://index.docker.io/v1/": { "auth": "{{mysecret | b64encode}}" } } }'
    kube_config: ''  # passed while calling this playbook
    install_name: 'docker-secrets'
    helm_chart: '{{charts_root}}/docker-secrets'
    is_template: true  
    helm_namespace: default
    helm_strings: 'dockerConfigJson={{dockerJson | to_json | b64encode}}'
    helm_values: '{{charts_root}}/docker-secrets/values.template.j2'
  roles:
    - {role:  helm, when: docker.hub.private == true}

