# This play installs all the MOSIP environment
#
- hosts: mzworker0  # One of the mz nodes is chosen for persistence
  gather_facts: true
  vars: 
    kube_config: '{{mz_kube_config}}'  
  tasks:
    - {name: 'Create folder', file: {name: '{{hdfs_dn_local_storage_path}}', state: directory}}
    - {name: 'Create folder', file: {name: '{{hdfs_nn_local_storage_path}}', state: directory}}

- hosts: console
  gather_facts: true
  vars:
    kube_config: '{{mz_kube_config}}'  # Deploy all these on mz cluster
  roles:
     # Base MOSIP infra
     - {role: helm, install_name: 'ingress-nginx', helm_chart: '{{charts_root}}/ingress-nginx', tags: [ingress]}
     - {role: helm, install_name: 'keycloak', helm_chart: '{{charts_root}}/keycloak', tags: [keycloak]}
     - {role: hdfs, tags: [hdfs]} # 
     - {role: clamav, tags: [clamav]} # 
     - {role: activemq, tags: [activemq]} # 
     - {role: keycloak-init, tags: [keycloak-init]}  

# Ingress controller on DMZ
- hosts: console
  gather_facts: true
  vars:
    kube_config: '{{dmz_kube_config}}'  # Deploy all these on mz cluster
  roles:
     # Base MOSIP infra
     - {role: helm, install_name: 'ingress-nginx', helm_chart: '{{charts_root}}/ingress-nginx', tags: [dmz-ingress]}

