# Playbook to enable grafana
# Inputs:  
#   mon_prop:  Monitor properties as in group_vars/all.yml
#   kube_config
- hosts: console
  tasks:
    - name: 'Create NFS folder'
      file: 
        name: '{{item.value}}'
        state: directory
        mode: '777' 
      become: yes
      with_items: '{{ mon_prop.nfs.grafana | dict2items }}'

- hosts: console
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: '{{ mon_prop.namespace}}'
        kubeconfig: '{{kube_config}}'
        api_version: v1
        kind: Namespace
        state: present

# Install Grafana
# Apply custom config
- hosts: console
  gather_facts: false
  tasks: 
    - name: Apply grafana custom config
      k8s:
        src: '{{charts_root}}/grafana/config.yaml'
        kubeconfig: '{{kube_config}}'
        namespace: '{{ mon_prop.namespace }}'
        state: present

- hosts: console
  vars:
    kube_config: '{{kube_config}}'
    install_name: 'graf'
    is_template: true  
    helm_chart: 'stable/grafana'
    helm_namespace: '{{ mon_prop.namespace }}'
    helm_values: '{{charts_root}}/grafana/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}
  
  tasks:
    - name: Get grafana token
      shell: 'kubectl --kubeconfig {{kube_config}}  get secret --namespace monitoring {{install_name}}-grafana -o jsonpath="{.data.admin-password}"  | base64 --decode ; echo'
      register: token

    - debug:
        msg: '{{token.stdout}}'
    
    - name: 'Copy token to {{mon_prop.grafana_token_file}}'
      copy:
        content: "{{token.stdout}}\n"
        dest: '{{mon_prop.grafana_token_file}}'

