# Softhsm.
- import_playbook: softhsm.yml 
  vars:
    kube_config: '{{clusters.mz.kube_config}}' 
    hsm_prop: '{{softhsm.ida}}'

# IDA
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: 'ida'
    helm_chart: '{{charts_root}}/ida'
    is_template: true  
    helm_namespace: 'default'
    helm_values: '{{charts_root}}/ida/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}
