# Playbook to install ELK component Kibana
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: kibana
    helm_chart: '{{charts_root}}/kibana'
    is_template: false
    helm_namespace: monitoring
    helm_values: '{{charts_root}}/kibana/values.yaml'
    helm_strings: ''
  roles:
    - {role:  helm}



