- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: 'mock-abis'
    helm_chart: '{{charts_root}}/mock-abis'
    is_template: true  
    helm_namespace: default
    helm_values: '{{charts_root}}/mock-abis/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}
