# This play installs all PreReg services using Helm
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: 'prereg'
    helm_chart: '{{charts_root}}/prereg'
    is_template: true  
    helm_namespace: 'default'
    helm_values: '{{charts_root}}/prereg/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}
