# All plays related to registration processor module
#

# Prep
- hosts: nfsserver
  tasks:
    - {name: 'Create landing folder', file: {name: '{{regproc.landing_folder}}', state: directory}, become: yes}

# Run DMZ regproc
- hosts: console
  gather_facts: true
  vars:   
    kube_config: '{{dmz_kube_config}}' 
    helm_chart: '{{charts_root}}/dmzregproc'
    install_name: dmzregproc
  roles:
    - {role: helm, tags: [dmzregproc]} 

## Run MZ regproc
#- hosts: console
#  gather_facts: true
#  vars:   
#    kube_config: '{{mz_kube_config}}' 
#    helm_chart: '{{charts_root}}/regproc'
#    install_name: regproc 
#  roles:
#    - {role: helm, tags: [regproc]} 
 
