# Playbook to install softhsm
# Inputs:
#   hsm_prop structure
#   kube_config  
# 

# Prepare folders on remote node
- hosts: console
  gather_facts: true
  vars:
    hsm_prop: '{{hsm_prop}}'
  roles:
    - {role: softhsm-prep}

# Convert helm template to helm values 
- hosts: console
  vars:
    kube_config: '{{kube_config}}'
    install_name: 'softhsm-{{hsm_prop.label}}' 
    helm_chart: '{{charts_root}}/softhsm'
    is_template: true  
    helm_namespace: 'default'
    helm_values: '{{charts_root}}/softhsm/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}

