apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.booking.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.booking.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: {{ .Values.services.booking.podconfig.replicas }} 
  selector:
    matchLabels:
      app: {{ .Values.services.booking.serviceName }} 
  minReadySeconds: {{ .Values.services.booking.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.booking.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.booking.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.booking.serviceName }} 
        component: {{ .Values.component }} 
    spec:
      containers:
      - name: {{ .Values.services.booking.serviceName }} 
        image: {{ .Values.services.booking.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{ $resources := .Values.services.application.podconfig.resources }}
        {{- include "resourcesDefinition" (dict "res" $resources) | indent 8 }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }}
        - name: iam_adapter_url_env
          value: {{ .Values.iamAdapterUrl }}
        - name: mosipbox_public_url
          value: {{ .Values.sitePublicUrl }}
        ports:
        - containerPort: {{ .Values.services.booking.containerPort }}


        readinessProbe:
          tcpSocket:
            port: {{ .Values.services.booking.containerPort }}
