apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.transliteration.serviceName }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.services.transliteration.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.transliteration.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.transliteration.serviceName }} 
        component: {{ .Values.component }} 
    spec:
      containers:
      - name: {{ .Values.services.transliteration.serviceName }} 
        image: {{ .Values.services.transliteration.dockerImage }}:{{ .Values.services.transliteration.dockerTag }} 
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: absent
        ports:
        - containerPort: {{ .Values.services.transliteration.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.transliteration.healthUrl }}
            port: {{ .Values.services.transliteration.containerPort }}
          initialDelaySeconds: {{ .Values.probe.initialDely }} 
          periodSeconds: {{ .Values.probe.periodSeconds }} 
        livenessProbe:
          httpGet:
            path: {{ .Values.services.transliteration.healthUrl }}
            port: {{ .Values.services.transliteration.containerPort }}
          initialDelaySeconds: {{ .Values.probe.initialDely }} 
          periodSeconds: {{ .Values.probe.periodSeconds }} 
