---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-applicanttype-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kernel-applicanttype-service
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: kernel-applicanttype-service
    spec:
      containers:
      - name: kernel-applicanttype-service
        image: docker-registry.mosip.io:5000/kernel-applicanttype-service:1.0.6-SNAPSHOT.96
        env:
        - name: active_profile_env
          value: qa
        - name: spring_config_label_env
          value: master
        - name: spring_config_url_env
          value: http://kernel-config-server:51000/config
        - name: artifactory_url_env
          value: http://13.71.87.138:8040
        - name: is_glowroot_env
          value: absent
        ports:
        - containerPort: 8094
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: kernel-applicanttype-service
  namespace: default
spec:
  ports:
    - port: 8094
  selector:
    app: kernel-applicanttype-service
  type: NodePort