---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-licensekeymanager-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kernel-licensekeymanager-service
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: kernel-licensekeymanager-service
    spec:
      initContainers:
      - name: wait-for-config-server
        image: centos:centos7
        command: [ "sh", "-c"]
        args:
        - while [ $(curl -sw '%{http_code}' $spring_config_url_env/actuator/health -o /dev/null) -ne 200 ]; do
            echo "config server not up at address $spring_config_url_env sleeping for 15 secs" ;
            sleep 15;
          done;
        env:
         - name: spring_config_url_env
           value: http://kernel-config-server:51000/config
      containers:
      - name: kernel-licensekeymanager-service
        image: docker-registry.mosip.io:5000/kernel-licensekeymanager-service:1.0.6-SNAPSHOT.96
        env:
        - name: active_profile_env
          value: qa
        - name: spring_config_label_env
          value: master
        - name: spring_config_url_env
          value: http://kernel-config-server:51000/config
        - name: artifactory_url_env
          value: http://13.71.87.138:8040
        - name: is_glowroot_env
          value: absent
        ports:
        - containerPort: 8093
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: kernel-licensekeymanager-service
  namespace: default
spec:
  ports:
    - port: 8093
  selector:
    app: kernel-licensekeymanager-service
  type: NodePort

