# Common task to install a Helm release (package) on kubernetes
# Parameters:
#   kube_config
#   install_name
#   helm_chart
#   template: true  # Convert j2 template to yaml 
#   helm_values: j2 template or yaml helm file
#   helm_strings: Key value pairs as per --set-strings option
#   helm_namespace: default if not specified

- include_vars: '{{versions_file}}' # Need for resolving various versions
- include_vars: '{{podconfig_file}}' # Configs of pods of all services

- name: Convert values template to values file
  template:
    src: '{{helm_values}}'
    dest: '{{helm_values | dirname}}/values.yaml'  # CAUTION: Writes in the same location. Name repeated below. 
  when: is_template == true  
  
- name: 'Check if {{install_name}} is already running'
  command: '{{helm_cli_path}}/helm --kubeconfig {{kube_config}} list -n {{helm_namespace}} -q'
  register: out

- debug:
    msg: '{{install_name}} already running'
  when: install_name in out.stdout.split()

- name: install chart
  block:
  - name: 'Install chart {{install_name}}'
    shell: '{{helm_cli_path}}/helm --kubeconfig {{kube_config}} install {{install_name}} {{helm_chart}} -f {{helm_values | dirname}}/values.yaml -n {{helm_namespace}} --create-namespace --set-string dummy=value,{{helm_strings}} --wait --timeout 20m0s --debug > {{tmp_yamls}}/{{install_name}}.yaml'
    when: install_name not in out.stdout.split()
    register: helm_out 
  
  - debug:
      msg: '{{helm_out.stdout}}'

  when: install_name not in out.stdout.split()
