apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.datashare.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.datashare.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  {{ $podconfig := .Values.services.datashare.podconfig }}
  replicas: {{ $podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.datashare.serviceName }}
  minReadySeconds: {{ $podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ $podconfig.maxUnavailable }}
      maxSurge: {{ $podconfig.maxSurge }}
  template:
    metadata:
      annotations:
        prometheus.io/path: {{ .Values.services.datashare.annotation }}
        prometheus.io/port: {{ .Values.services.datashare.ports.containerPort | quote }}
        prometheus.io/scrape: "'true'"
      labels:
        app: {{ .Values.services.datashare.serviceName }} 
        component: {{ .Values.component }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.datashare.serviceName }} 
        image: {{ .Values.services.datashare.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- include "resourcesDefinition" (dict "res" $podconfig.resources) | indent 8 }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: iam_adapter_url_env
          value: {{ .Values.iamAdapterUrl }}
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }} 
        - name: iam_adapter_url_env
          value: {{ .Values.iamAdapterUrl }}
        - name: JDK_JAVA_OPTIONS
          value: {{ $podconfig.java_opts }}
        ports:
        - containerPort: {{ .Values.services.datashare.ports.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.datashare.healthUrl }}
            port: {{ .Values.services.datashare.ports.containerPort }}
          periodSeconds: {{ .Values.probe.period }}
          timeoutSeconds: {{ .Values.probe.timeout }}
        livenessProbe:
          httpGet:
            path: {{ .Values.services.datashare.healthUrl }}
            port: {{ .Values.services.datashare.ports.containerPort }}
          periodSeconds: {{ .Values.probe.livenessPeriod }}
          timeoutSeconds: {{ .Values.probe.timeout }}
        startupProbe:
          httpGet:
            path: {{ .Values.services.datashare.healthUrl }}
            port: {{ .Values.services.datashare.ports.containerPort }}
          failureThreshold: {{ .Values.probe.failureThreshold }}
          periodSeconds: {{ .Values.probe.startupPeriod }}
