---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{  .Values.name }}
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: {{ .Values.services.clamav.podconfig.replicas }} 
  selector:
    matchLabels:
      app: {{ .Values.name }} 
  minReadySeconds: {{ .Values.services.clamav.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.clamav.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.clamav.podconfig.maxSurge }} 
  template:
    metadata:
      labels:
        app: {{ .Values.name }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      containers:
      - name: {{  .Values.name }}
        image: {{ .Values.docker.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{ $resources := .Values.services.clamav.podconfig.resources }}
        {{- include "resourcesDefinition" (dict "res" $resources) | indent 8 }}
        ports:
        - containerPort: {{ .Values.docker.containerPort }}
        readinessProbe:
          tcpSocket:
            port: {{  .Values.docker.containerPort }}

