image:
  registry: docker.io
  repository: mosipint/keys-generator
  tag: 1.2.0-rc2
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ## 
  pullPolicy: Always
