apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  annotations:
     kubernetes.io/ingress.class: "nginx"
    # nginx.com/health-checks: "true"
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.services.mosip_file_server.ingressPath_well_known }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.serviceName }}
            port: 
              number: 80 

      - path: {{ .Values.services.mosip_file_server.ingressPath_files }}
        pathType: ImplementationSpecific
        backend:
            service:
                name: {{ .Values.serviceName }}
                port:
                    number: 80
