apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }} 
  namespace: {{ .Release.Namespace }} 
spec:
  ports:
  - port: {{ .Values.docker.ports.servicePort }}
    targetPort: {{ .Values.docker.ports.containerPort }}
  selector:
    app: {{ .Values.serviceName }} 

