---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.services.keycloak.podconfig.replicas }} 
  selector:
    matchLabels:
      app: {{ .Values.name }}
  minReadySeconds: {{ .Values.services.keycloak.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.keycloak.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.keycloak.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        exportLogs: {{ .Values.exportLogs }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.dockerImage }}:{{ .Values.dockerTag }} 
        env:
        - name: KEYCLOAK_USER 
          value: {{ .Values.keycloakUser }}
        - name: KEYCLOAK_PASSWORD 
          value: {{ .Values.keycloakPassword }}
        - name: DB_VENDOR 
          value: postgres
        - name: DB_DATABASE
          value: {{ .Values.db.name }} 
        - name: DB_ADDR
          value: {{ .Values.db.host }} 
        - name: DB_PORT
          value: "{{ .Values.db.port }}" 
        - name: DB_USER 
          value: {{ .Values.db.user }} 
        - name: DB_PASSWORD
          value: {{ .Values.db.password }} 
        - name: KEYCLOAK_FRONTEND_URL
          value: {{ .Values.keycloakExternalUrl }}  
        ports:
        - containerPort: {{ .Values.containerPort }} 
        readinessProbe:
          tcpSocket:
            port: {{ .Values.containerPort }}  # All defaults used

