podconfig:
  kernel:
    auth:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    masterdata:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    idgen:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    prid:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    sync:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    audit :
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    key:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    notifier:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    otp:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    rid:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    keyMigrator:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  regproc:
    camel:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    group2:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 300m
          memory: 2Gi
        limits:
          cpu: 500m
          memory: 4Gi

    group3:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 300m
          memory: 2Gi
        limits:
          cpu: 500m
          memory: 4Gi

    group4:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    group5:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 300m
          memory: 2Gi
        limits:
          cpu: 500m
          memory: 4Gi

    group6:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    group7:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    trans:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    workflow:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    reprocess:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    notificationService: 
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  dmzregproc:  
    group1:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    camel:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    status:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    pktserver:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  prereg:
    application:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    batch:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    booking:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi
    datasync:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    captcha:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    ui:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1  
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  ida:
    auth:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    internal: 
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    otp: 
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  idrepo:
    identity:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    vid: 
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    credentialreq:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    credentialservice:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  pms:
    partner:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    policy:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  packetmanager:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi
  resident:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  activemq:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi
  admin:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    hotlist:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  artifactory:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  clamav:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  config_server:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  datashare:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  docker_service:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  keycloak:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 600m
          memory: 1.5Gi
  mockabis:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 400m
          memory: 700Mi 

  mockmv:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 400m
          memory: 700Mi

  postgres:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 1000m
          memory: 1.5Gi
  print:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  reg_client_downloader:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 300m
          memory: 1.5Gi
        limits:
          cpu: 500m
          memory: 1.5Gi

  websub:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

    consolidator:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  mosip_file_server:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  tusd:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  resident_app_server:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms750M -Xmx750M"
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi
        limits:
          cpu: 300m
          memory: 1.5Gi

  ingress:
    nginx:
      replicas: 1 
