podconfig:
  kernel:
    auth:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms1000M -Xmx1000M"
 
    masterdata:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    idgen:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms500M -Xmx500M"
 
    prid:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms500M -Xmx500M"

    sync:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    audit :
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    key:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    notifier:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    otp:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    rid:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

  regproc:
    camel:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"
 
    notification: 
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    uploader:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"
 
    quality:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"
 
    validator:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"
 
    osi:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    demo:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    bio:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    bioauth:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    abishandler:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    abismid:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    manual:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    external:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    eis: 
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    uin:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    msg:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    print:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    trans:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    reprocess:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

  dmzregproc:  
    receiver:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    camel:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    status:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    pktserver:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

  prereg:
    application:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms500M -Xmx500M"

    batch:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms500M -Xmx500M"
  
    booking:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1
      java_opts: "-Xms500M -Xmx500M"
 
    datasync:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms500M -Xmx500M"

    ui:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1  
      java_opts: "-Xms500M -Xmx500M"

  ida:
    auth:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    internal: 
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    kyc: 
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms500M -Xmx500M"

    otp: 
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

  idrepo:
    identity:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    vid: 
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    bioextractor:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    credentialreq:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      java_opts: "-Xms500M -Xmx500M"

    credentialservice:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      java_opts: "-Xms500M -Xmx500M"

  pms:
    misp: 
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"
 
    pm:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

    partner:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"
 
    policy:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

  packetmanager:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"
  
  resident:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"
  
  activemq:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  admin:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

  artifactory:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
  
  clamav:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  config_server:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
  
  datashare:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      java_opts: "-Xms500M -Xmx500M"

  docker_service:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  keycloak:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  mockabis:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 400m
          memory: 700Mi 

  postgres:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  print:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  reg_client_downloader:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  websub:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  ingress:
    nginx:
      replicas: 1 
