# this is for installing kafka with zookeeper from bitnami charts
# if not preinstalled, enable these
bitnami-kafka:
  enabled: true
  zookeeper:
    enabled: true

# This is for debezium kafka connector
debezium:
  enabled: true
  # If kafka is preinstalled, specify how it can be reached here
  # kafka:
  #   server: "kafka:9092"

# This is for elasticsearch kafka connector
confluentinc:
  enabled: true
  cp-kafka-connect:
    enabled: true
    # If kafka is preinstalled, specify how it can be reached here
    # kafka:
    #   bootstrapServers: kafka.kafka:9092
    # configurationOverrides:
    #   zookeeper.connect: zookeeper:2181

# this is for kafkaClient
kafkaClient:
  enabled: true
  # the following is when no secret is to be used from db_pass
  db_secretref: null

bitnami-elasticsearch:
  enabled: false
