apiVersion: v1
data:
  config.json: "{\r\n \"BASE_URL\":\"http://<yourPrivateIp>/\",\r\n \"PRE_REG_URL\":\"preregistration/v1/\"\r\n}"
kind: ConfigMap
metadata:
  name: pre-registration-ui-configuration
  namespace: default
