apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.camel.serviceName }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.services.camel.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.camel.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.camel.serviceName }} 
        component: {{ .Values.component }} 
    spec:
      containers:
      - name: {{ .Values.services.camel.serviceName }} 
        image: {{ .Values.services.camel.dockerImage }}:{{ .Values.services.camel.dockerTag }} 
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: absent
        ports:
        - name: eventbus-port
          containerPort: {{ .Values.services.camel.ports.eventbusPort }}
        - name: hazelcast-port
          containerPort: {{ .Values.services.camel.ports.hazelcastPort }}
        - name: verticle-port
          containerPort: {{ .Values.services.camel.ports.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.camel.healthUrl }} 
            port: {{ .Values.services.camel.ports.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
        livenessProbe:
          httpGet:
            path: {{ .Values.services.camel.healthUrl }} 
            port: {{ .Values.services.camel.ports.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
