apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.receiver.serviceName }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.services.receiver.serviceName }}
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.receiver.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.receiver.serviceName }} 
        component: service-hazelcast-server
    spec:
      containers:
      - name: {{ .Values.services.receiver.serviceName }} 
        image: {{ .Values.services.receiver.dockerImage }}:{{ .Values.services.receiver.dockerTag }} 
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: absent
        ports:
        - name: eventbus-port
          containerPort: {{ .Values.services.receiver.ports.eventbusPort }}
        - name: hazelcast-port
          containerPort: {{ .Values.services.receiver.ports.hazelcastPort }}
        - name: verticle-port
          containerPort: {{ .Values.services.receiver.ports.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.receiver.healthUrl }} 
            port: {{ .Values.services.receiver.ports.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
        livenessProbe:
          httpGet:
            path: {{ .Values.services.receiver.healthUrl }} 
            port: {{ .Values.services.receiver.ports.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
        volumeMounts:
        - name: landing-zone
          mountPath: {{ .Values.landing.path }}
        - name: archival-zone
          mountPath: {{ .Values.archival.path }}
      volumes:
      - name: landing-zone
        persistentVolumeClaim:
          claimName: {{ .Values.landing.pvcName }}
      - name: archival-zone
        persistentVolumeClaim:
          claimName: {{ .Values.archival.pvcName }}
