apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.mockabis.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.mockabis.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: {{ .Values.services.mockabis.podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.mockabis.serviceName }} 
  minReadySeconds: {{ .Values.services.mockabis.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.mockabis.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.mockabis.podconfig.maxSurge }}
  template:
    metadata:
      annotations:
        prometheus.io/path: {{ .Values.services.mockabis.annotation }}
        prometheus.io/port: {{ .Values.services.mockabis.ports.containerPort | quote }}
        prometheus.io/scrape: "'true'"
      labels:
        app: {{ .Values.services.mockabis.serviceName }} 
        component: {{ .Values.component }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.mockabis.serviceName }} 
        image: {{ .Values.services.mockabis.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{ $resources := .Values.services.mockabis.podconfig.resources }}
        {{- include "resourcesDefinition" (dict "res" $resources) | indent 8 }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }} 
        ports:
        - containerPort: {{ .Values.services.mockabis.ports.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.mockabis.healthUrl }}
            port: {{ .Values.services.mockabis.ports.containerPort }}
          periodSeconds: {{ .Values.probe.period }}
          timeoutSeconds: {{ .Values.probe.timeout }}
        livenessProbe:
          httpGet:
            path: {{ .Values.services.mockabis.healthUrl }}
            port: {{ .Values.services.mockabis.ports.containerPort }}
          periodSeconds: {{ .Values.probe.livenessPeriod }}
          timeoutSeconds: {{ .Values.probe.timeout }}
        startupProbe:
          httpGet:
            path: {{ .Values.services.mockabis.healthUrl }}
            port: {{ .Values.services.mockabis.ports.containerPort }}
          failureThreshold: {{ .Values.probe.failureThreshold }}
          periodSeconds: {{ .Values.probe.startupPeriod }}
        volumeMounts:
        - name: p12-key
          mountPath: /home/mosip/keystore  # Hardcoded in Dockerfile
      volumes:
      - name: p12-key
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
