apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.print.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.print.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: {{ .Values.services.print.podconfig.replicas }} 
  selector:
    matchLabels:
      app: {{ .Values.services.print.serviceName }} 
  minReadySeconds: {{ .Values.services.print.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.print.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.print.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.print.serviceName }} 
        component: {{ .Values.component }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.print.serviceName }} 
        image: {{ .Values.services.print.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }} 
        ports:
        - containerPort: {{ .Values.services.print.containerPort }}

        {{- include "logger.mount" .  | indent 8}}

        readinessProbe:
          httpGet:
            path: {{ .Values.services.print.healthUrl }} 
            port: {{ .Values.services.print.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
  #      livenessProbe:
  #        httpGet:
  #          path: {{ .Values.services.print.healthUrl }} 
  #          port: {{ .Values.services.print.containerPort }} 
  #        initialDelaySeconds: {{ .Values.probe.initialDelay }} 
  #        periodSeconds: {{ .Values.probe.period }}
  #
      {{- include "logger.sidecar" .  | indent 6}}

      {{- include "logger.volume" .  | indent 6}}
