apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.audit.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.audit.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  {{ $podconfig := .Values.services.audit.podconfig }}
  replicas: {{ $podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.audit.serviceName }}
  minReadySeconds: {{ $podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ $podconfig.maxUnavailable }}
      maxSurge: {{ $podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.audit.serviceName }} 
        component: {{ .Values.component }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.audit.serviceName }} 
        image: {{ .Values.services.audit.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- include "resourcesDefinition" (dict "res" $podconfig.resources) | indent 8 }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }} 
        - name: iam_adapter_url_env
          value: {{ .Values.iamAdapterUrl }}
        - name: JDK_JAVA_OPTIONS
          value: {{ $podconfig.java_opts }}
        ports:
        - containerPort: {{ .Values.services.audit.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.audit.healthUrl }} 
            port: {{ .Values.services.audit.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
   #     livenessProbe:
   #       httpGet:
   #         path: {{ .Values.services.audit.healthUrl }} 
   #         port: {{ .Values.services.audit.containerPort }} 
   #       initialDelaySeconds: {{ .Values.probe.initialDelay }} 
   #       periodSeconds: {{ .Values.probe.period }}
