apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.auth.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.auth.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.auth.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.auth.serviceName }} 
        component: {{ .Values.component }} 
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.auth.serviceName }} 
        image: {{ .Values.services.auth.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }} 
        - name: iam_adapter_url_env
          value: {{ .Values.iamAdapterUrl }}
        ports:
        - containerPort: {{ .Values.services.auth.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.auth.healthUrl }} 
            port: {{ .Values.services.auth.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
  #      livenessProbe:
  #        httpGet:
  #          path: {{ .Values.services.auth.healthUrl }} 
  #          port: {{ .Values.services.auth.containerPort }} 
  #        initialDelaySeconds: {{ .Values.probe.initialDelay }} 
  #        periodSeconds: {{ .Values.probe.period }}
