global:
  kibanaEnabled: true
data:
  heapSize: 728m
  persistence:
    enabled: true
    size: 16Gi
  resources:
    requests:
      memory: 512Mi
master:
  heapSize: 1024m
  persistence:
    enabled: true
    size: 16Gi
  resources:
    requests:
      memory: 728Mi
kibana:
  persistence:
    enabled: false
