---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-processor-uin-generator-stage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-processor-uin-generator-stage
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: registration-processor-uin-generator-stage
        component: service-hazelcast-server
    spec:
      initContainers:
      - name: wait-for-config-server
        image: centos:centos7
        command: [ "sh", "-c"]
        args:
        - while [ $(curl -sw '%{http_code}' $spring_config_url_env/actuator/health -o /dev/null) -ne 200 ]; do
            echo "config server not up at address $spring_config_url_env sleeping for 15 secs" ;
            sleep 15;
          done;
        env:
         - name: spring_config_url_env
           value: http://kernel-config-server:51000/config
      containers:
      - name: registration-processor-uin-generator-stage
        image: mosipid/registration-processor-uin-generator-stage:1.0.6
        ports:
          - name: eventbus-port
            containerPort: 5719
        ports:
          - name: hazelcast-port
            containerPort: 5701
        ports:
          - name: verticle-port
            containerPort: 8099
        env:
        - name: active_profile_env
          value: qa
        - name: spring_config_label_env
          value: master
        - name: spring_config_url_env
          value: http://kernel-config-server:51000/config
        imagePullPolicy: Always
      imagePullSecrets:
      - name: pvt-reg-cred
---
apiVersion: v1
kind: Service
metadata:
  name: registration-processor-uin-generator-stage
  namespace: default
spec:
  ports:
  - port: 8099
  selector:
    app: registration-processor-uin-generator-stage
