# Reset landing zone 
- hosts: console
  gather_facts: no
  become: yes
  vars_prompt:
    - name: sure 
      prompt: 'Do you want to ERASE LANDING ZONE? All packets will be lost.  Are you sure? (yes/no)' 
      private: no
  tasks:
   - name: Delete landing zone
     file: 
       path: '{{regproc.nfs.landing_folder}}'
       state: absent     
     when: sure.lower().strip() == 'yes'
     become: yes
