- hosts: console
  gather_facts: no
  become: yes
  vars_prompt:
    - name: sure 
      prompt: 'Do you want to ERASE all SOFTHSM keys and data? Are you sure? (yes/no)'
      private: no
  tasks:
   - name: Delete all keymanager softhsm data
     file: 
       path: '{{softhsm.keymanager.nfs_path}}'
       state: absent     
     when: sure.lower().strip() == 'yes'

   - name: Delete all ida softhsm data
     file: 
       path: '{{softhsm.ida.nfs_path}}'
       state: absent     
     when: sure.lower().strip() == 'yes'
