apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }} 
  label:
    name: {{ .Values.pv.name }} 
spec:
  storageClassName: {{ .Values.sc.name }} 
  capacity:
    storage: {{ .Values.pv.size }}
  accessModes:
    - ReadWriteOnce
  nfs:
    server:  {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }} 
