istio:
  name: minio
  host: minio.sandbox.xyz.net
# Note: If you have multiple ingressController then pass it in the form of list.
  ingressController: <istio-ingressgateway>
# Note : By default, if you do **not** specify any gateways, the chart will bind to a single Gateway whose name is derived from the metadata name. If you have mutiple gateways to specify then pass it in the form of list like below.
# gateways:
#   - public-gateway
#   - internal-gateway
  port:
    protocol: HTTP

  servers:
    # HTTP on port 80
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - minio.sandbox.xyz.net
    # MinIO API on port 9000
    - port:
        name: minio
        number: 9000
        protocol: HTTP
      hosts:
        - minio.sandbox.xyz.net

  httpRoutes:
    # match on port 9000, send to port 9000
    - name: minio
      match:
        port: 9000
      destination:
        host: minio
        port: 9000

    # match on URI “/”, send to port 9001
    - name: http
      match:
        uriPrefix: "/"
      destination:
        host: minio
        port: 9001
