keycloak_mosip_realms:
  - {realm_id: 'master', realm_file: 'realms/realm_master.json'}  # Only to update Master settings
  - {realm_id: 'mosip', realm_file: 'realms/realm_mosip.json'}
  - {realm_id: 'preregistration', realm_file: 'realms/realm_prereg.json'}

# IMPORTANT: If the client secret is changed below make sure you update the corresponding property in the property files of config-server. 
keycloak_mosip_clients:
  - {realm_id: 'mosip', client_id: 'mosip-admin-client', secret: 'xyz123'}  
  - {realm_id: 'mosip', client_id: 'mosip-auth-client', secret: 'abc123'}  
  - {realm_id: 'mosip', client_id: 'mosip-prereg-client', secret: 'abc123'}  # TODO: To be removed later after client-realm bugfix.
  - {realm_id: 'preregistration', client_id: 'mosip-prereg-client', secret: 'abc123'} 
  - {realm_id: 'mosip', client_id: 'mosip-regproc-client', secret: 'abc123'} 
  - {realm_id: 'mosip', client_id: 'mosip-ida-client', secret: 'abc123'} 
  - {realm_id: 'mosip', client_id: 'mosip-reg-client', secret: 'abc123'} 

keycloak_mosip_roles:  # Currently, all rolese belong to a realm (not to any client)
  - {realm_id: 'mosip', client_id: '', role_name: 'REGISTRATION_OFFICER'}
  - {realm_id: 'mosip', client_id: '', role_name: 'ID_AUTHENTICATION'}
  - {realm_id: 'mosip', client_id: '', role_name: 'DEVICE_PROVIDER'}
  - {realm_id: 'mosip', client_id: '', role_name: 'SUPERADMIN'}
  - {realm_id: 'mosip', client_id: '', role_name: 'ZONAL_ADMIN'}
  - {realm_id: 'mosip', client_id: '', role_name: 'GLOBAL_ADMIN'}
  - {realm_id: 'mosip', client_id: '', role_name: 'RESIDENT'}
  - {realm_id: 'mosip', client_id: '', role_name: 'REGISTRATION_PROCESSOR'}
  - {realm_id: 'mosip', client_id: '', role_name: 'ZONAL_APPROVER'}
  - {realm_id: 'mosip', client_id: '', role_name: 'REGISTRATION_OFFICER'}
  - {realm_id: 'mosip', client_id: '', role_name: 'REGISTRATION_OPERATOR'}
  - {realm_id: 'mosip', client_id: '', role_name: 'AUTH'}
  - {realm_id: 'mosip', client_id: '', role_name: 'CENTRAL_APPROVER'}
  - {realm_id: 'mosip', client_id: '', role_name: 'MISP'}
  - {realm_id: 'mosip', client_id: '', role_name: 'CENTRAL_ADMIN'}
  - {realm_id: 'mosip', client_id: '', role_name: 'PREREG'}
  - {realm_id: 'mosip', client_id: '', role_name: 'PRE_REGISTRATION_ADMIN'}
  - {realm_id: 'mosip', client_id: '', role_name: 'PRE_REGISTRATION'}
  - {realm_id: 'mosip', client_id: '', role_name: 'REGISTRATION_ADMIN'}
  - {realm_id: 'mosip', client_id: '', role_name: 'REGISTRATION_SUPERVISOR'}
  - {realm_id: 'mosip', client_id: '', role_name: 'INDIVIDUAL'}  # TODO: later this role should not be needed in mosip realm
  - {realm_id: 'preregistration', client_id: '', role_name: 'INDIVIDUAL'}
  - {realm_id: 'preregistration', client_id: '', role_name: 'AUTH'}
  - {realm_id: 'preregistration', client_id: '', role_name: 'PRE_REGISTRATION_ADMIN'}
  - {realm_id: 'preregistration', client_id: '', role_name: 'PREREG'}

keycloak_mosip_users: # Assumption "username.json" exists with same username inside 
  - {realm_id: 'mosip', user_file: 'users/testuser.json'}

keycloak_mosip_user_role_map:  
  - {realm_id: 'mosip', username: 'testuser', role_name: 'REGISTRATION_OFFICER'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'ID_AUTHENTICATION'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'DEVICE_PROVIDER'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'SUPERADMIN'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'ZONAL_ADMIN'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'GLOBAL_ADMIN'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'RESIDENT'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'REGISTRATION_PROCESSOR'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'ZONAL_APPROVER'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'REGISTRATION_OFFICER'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'REGISTRATION_OPERATOR'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'AUTH'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'CENTRAL_APPROVER'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'MISP'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'PREREG'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'CENTRAL_ADMIN'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'PRE_REGISTRATION'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'PRE_REGISTRATION_ADMIN'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'REGISTRATION_ADMIN'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'REGISTRATION_SUPERVISOR'}
  - {realm_id: 'mosip', username: 'testuser', role_name: 'RESIDENT'}
    # For service account mappings client name must be prefixed with service-account-
  - {realm_id: 'mosip', username: 'service-account-mosip-prereg-client', role_name: 'INDIVIDUAL'}
  - {realm_id: 'mosip', username: 'service-account-mosip-prereg-client', role_name: 'PRE_REGISTRATION_ADMIN'}
  - {realm_id: 'mosip', username: 'service-account-mosip-prereg-client', role_name: 'PREREG'}
  - {realm_id: 'preregistration', username: 'service-account-mosip-prereg-client', role_name: 'INDIVIDUAL'}
  - {realm_id: 'preregistration', username: 'service-account-mosip-prereg-client', role_name: 'PRE_REGISTRATION_ADMIN'}
  - {realm_id: 'preregistration', username: 'service-account-mosip-prereg-client', role_name: 'PREREG'}
  - {realm_id: 'mosip', username: 'service-account-mosip-auth-client', role_name: 'AUTH'}
  - {realm_id: 'mosip', username: 'service-account-mosip-regproc-client', role_name: 'REGISTRATION_PROCESSOR'}
  - {realm_id: 'mosip', username: 'service-account-mosip-ida-client', role_name: 'ID_AUTHENTICATION'}
  - {realm_id: 'mosip', username: 'service-account-mosip-reg-client', role_name: 'GLOBAL_ADMIN'}
  - {realm_id: 'mosip', username: 'service-account-mosip-reg-client', role_name: 'REGISTRATION_ADMIN'}
  - {realm_id: 'mosip', username: 'service-account-mosip-reg-client', role_name: 'REGISTRATION_OFFICER'}
  - {realm_id: 'mosip', username: 'service-account-mosip-reg-client', role_name: 'REGISTRATION_OPERATOR'}
  - {realm_id: 'mosip', username: 'service-account-mosip-reg-client', role_name: 'REGISTRATION_SUPERVISOR'}

