apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }} 
  labels:
    name: {{ .Values.pv.name }} 
spec:
  capacity:
    storage: {{ .Values.pv.size }}
  accessModes:
    - ReadWriteOnce
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }} 
