- name: Install nginx
  yum:
    name: nginx
    state: present
  become: yes

- name: Copy the default nginx conf file
  copy:
    src: 'nginx.default.conf'
    dest: '/etc/nginx/nginx.conf'
  become: yes

# TODO: It's assumed that firewall is disbled, so remove this code
# if it works well.  Note that CentOS 7.8 does not have firewalld enabled
# by default
#
#- name: Enable firewall for http
#  firewalld:
#    service: http
#    permanent: yes
#    state: enabled
#  become: yes
#
#- name: Enable firewall for https
#  firewalld:
#    service: https
#    permanent: yes
#    state: enabled
#  become: yes 

- name: Restart nginx
  command: 'systemctl restart nginx'
  become: yes

- name: allow selinux to connect to httpd
  # Note: otherwise selinux prevents it. TODO: find ansible way of doing this
  command: 'setsebool httpd_can_network_connect on -P'
  become: yes
   
# For external connection to postgres via nginx
- name: 'allow nginx to access port {{postgres.nodeport}}'
  seport:
    ports: '{{postgres.nodeport}}'
    proto: tcp
    setype: http_port_t
    state: present
  become: yes

# For external connection to activemq via nginx
- name: 'allow nginx to access activemq port {{activemq.nodeport}}'
  seport:
    ports: '{{activemq.nodeport}}'
    proto: tcp
    setype: http_port_t
    state: present
  become: yes

