# Tasks to update nginx conf file and restart nginx
#

- include_vars: '{{versions_file}}' # Need for resolving various versions

- name: nginx conf template {{nginx_conf_template}} to yml 
  template:
    src: '{{nginx_conf_template}}'
    dest: '{{tmp_dir}}/nginx.conf'

- name: Copy new conf file
  copy:
    src: '{{tmp_dir}}/nginx.conf'
    dest: '/etc/nginx'
  become: yes

- name: nginx index.html template to yaml
  template:
    src: nginx_index.yml.j2
    dest: '{{tmp_dir}}/nginx_index.html'

- name: Copy index file
  copy:
    src: '{{tmp_dir}}/nginx_index.html'
    dest: '/usr/share/nginx/html/index.html'
  become: yes

- name: Set symlink to mosip versions file
  file: 
    src: '{{install_root}}/versions.yml'
    dest: '/usr/share/nginx/html/versions.txt'
    state: link
  become: yes

- name: Set symlink to regclient keys zip file
  file: 
    src: '{{install_root}}/roles/reg-client-prep/files/regclientkeys.zip'
    dest: '/usr/share/nginx/html/regclientkeys.zip'
    state: link
  become: yes

- name: Restart nginx
  command: 'systemctl restart nginx'
  become: yes
