apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.credentialrequest.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.credentialrequest.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: {{ .Values.services.credentialrequest.podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.credentialrequest.serviceName }} 
  minReadySeconds: {{ .Values.services.credentialrequest.podconfig.minReadySeconds }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.credentialrequest.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.credentialrequest.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.credentialrequest.serviceName }} 
        component: {{ .Values.component }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.credentialrequest.serviceName }} 
        image: {{ .Values.services.credentialrequest.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }}
        - name: mosipbox_public_url
          value: {{ .Values.sitePublicUrl }}
        ports:
        - containerPort: {{ .Values.services.credentialrequest.containerPort }}

        {{- include "logger.mount" .  | indent 8}}

        readinessProbe:
          httpGet:
            path: {{ .Values.services.credentialrequest.healthUrl }} 
            port: {{ .Values.services.credentialrequest.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
 #       livenessProbe:
 #         httpGet:
 #           path: {{ .Values.services.credentialrequest.healthUrl }} 
 #           port: {{ .Values.services.credentialrequest.containerPort }} 
 #         initialDelaySeconds: {{ .Values.probe.initialDelay }} 
 #         periodSeconds: {{ .Values.probe.period }}
 #
      {{- include "logger.sidecar" .  | indent 6}}

      {{- include "logger.volume" .  | indent 6}}
