apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.identity.serviceName }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.services.identity.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.services.identity.serviceName }} 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: {{ .Values.services.identity.serviceName }} 
        component: {{ .Values.component }} 
    spec:
      containers:
      - name: {{ .Values.services.identity.serviceName }} 
        image: {{ .Values.services.identity.dockerImage }}:{{ .Values.services.identity.dockerTag }} 
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: absent
        ports:
        - containerPort: {{ .Values.services.identity.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.services.identity.healthUrl }} 
            port: {{ .Values.services.identity.containerPort }} 
          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
          periodSeconds: {{ .Values.probe.period }} 
 #       livenessProbe:
 #         httpGet:
 #           path: {{ .Values.services.identity.healthUrl }} 
 #           port: {{ .Values.services.identity.containerPort }} 
 #         initialDelaySeconds: {{ .Values.probe.initialDelay }} 
 #         periodSeconds: {{ .Values.probe.period }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.services.identity.containerPort }}
