# Tasks here create and populate git repository on a node machine.
#
- name: Create git config repo dir 
  file:
    path: '{{config_repo_node_path}}' # Defined in role config-server
    state: directory 

- name: Copy properties files to node 
  copy:
     src: '../files/properties/'  
     dest: '{{config_repo_node_path}}' 
     force: no

#TODO: Repetition here.  Improve the code.
- import_tasks: templates.yml  # Deployment specific properites are overwritten here
  vars:
    prop_file: pre-registration-qa.properties

- import_tasks: templates.yml  # Deployment specific properites are overwritten here
  vars:
    prop_file: kernel-qa.properties

- name: Install git 
  yum:
    name: git
    state: present
    
- name: Git init
  command: 'git init' 
  args:
    chdir: '{{config_repo_node_path}}' 

- name: Git add
  command: 'git add .' 
  args:
    chdir: '{{config_repo_node_path}}' 

- name: Git add
  command:  'git -c user.email={{lookup("env", "USER")}}@mosip commit -m "Updated"' 
  args:
    chdir: '{{config_repo_node_path}}' 
  ignore_errors: yes
