- name: Install psql12 rpm
  yum: 
    name:  https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  become: yes

- name: Install psql12
  yum:
    name:  postgresql12
    state: present
  become: yes

