dbUserPasswords:
  dbuserPassword: ""

databases:
  mosip_master:
    enabled: true
    branch: release-1.2.0.1

  mosip_audit:
    enabled: true
    branch: release-1.2.0.1

  mosip_keymgr:
    enabled: true 
    branch: release-1.2.0.1

  mosip_kernel:
    enabled: true
    branch: release-1.2.0.1

  mosip_idmap:
    enabled: true
    branch: release-1.2.0.1

  mosip_prereg:
    enabled: true
    branch: release-1.2.0.1

  mosip_idrepo:
    enabled: true
    branch: release-1.2.0.1

  mosip_ida:
    enabled: true
    branch: release-1.2.0.1

  mosip_credential:
    enabled: true
    branch: release-1.2.0.1

  mosip_regprc:
    enabled: true
    branch: release-1.2.0.1

  mosip_pms:
    enabled: true
    branch: release-1.2.0.1

  mosip_hotlist:
    enabled: true
    branch: release-1.2.0.1

  mosip_resident:
    enabled: true
    branch: release-1.2.0.1

  mosip_toolkit:
    enabled: false
    branch: release-1.x.x
 
  mosip_digitalcard:
    enabled: false

  mosip_esignet:
    enabled: false

  mosip_mockidentitysystem:
    enabled: false
