dbUserPasswords:
  dbuserPassword: ""

databases:
  mosip_master:
    enabled: true
    branch: v1.2.0.1-B1

  mosip_audit:
    enabled: true
    branch: v1.2.0.1-B1

  mosip_keymgr:
    enabled: true
    branch: v1.2.0.1-B3

  mosip_kernel:
    enabled: true
    branch: v1.2.0.1-B1

  mosip_idmap:
    enabled: true
    branch: v1.2.0.1-B1

  mosip_prereg:
    enabled: true
    branch: v1.2.0.1-B1

  mosip_idrepo:
    enabled: true
    branch: v1.2.0.1-B1

  mosip_ida:
    enabled: true
    branch: 1.2.0.1-B5

  mosip_credential:
    enabled: true
    branch: v1.2.0.1-B1

  mosip_regprc:
    enabled: true
    branch: v1.2.0.1-B2

  mosip_pms:
    enabled: true
    branch: v1.2.0.1-B3

  mosip_hotlist:
    enabled: true
    branch: v1.2.0.1-B1

  mosip_resident:
    enabled: true
    branch: v1.2.0.1-B2
