bqatsdk:
  ## This is url of bqatsdk lib accessed from within cluster.  BqatSDK may be hosted outside the cluster
  ## in which case change the URL accordingly.
  zippedLibUrl: http://artifactory.artifactory/artifactory/libs-release-local/biosdk/bqatsdk-lib.jar
  bioapiImpl: io.bqat.sdk.services.impl.BqatQualitySdkService
